name: RPM Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: build Merlin package
      id: merlin
      uses: UCBoulder/oit-sepe-rpmbuild@master
      with:
        spec_file: "merlin.spec"
        additional_repos: '["epel-release", "https://labs.consol.de/repo/stable/rhel8/x86_64/labs-consol-stable.rhel8.noarch.rpm"]'

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Binary RPM
        path: ${{ steps.merlin.outputs.rpm_dir_path }}
