name: RPM Build
on: push

jobs:
  build-naemon:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: build Naemon packages
      id: naemon 
      uses: UCBoulder/oit-sepe-rpmbuild@master
      with:
        spec_file: "naemon-core.spec"
        additional_repos: '["epel-release"]'

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Naemon RPMs
        path: ${{ steps.naemon.outputs.rpm_dir_path }}

  build-merlin:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: build Merlin packages
      id: merlin
      uses: UCBoulder/oit-sepe-rpmbuild@master
      with:
        spec_file: "merlin.spec"
        additional_repos: '["epel-release", "https://labs.consol.de/repo/stable/rhel8/x86_64/labs-consol-stable.rhel8.noarch.rpm"]'

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Merlin RPMs
        path: ${{ steps.merlin.outputs.rpm_dir_path }}

