name: RPM Build
on: push

jobs:
  build-naemon:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: build Naemon packages
      id: naemon 
      uses: UCBoulder/oit-sepe-rpmbuild@master
      with:
        spec_file: "naemon-core.spec"
        additional_repos: '["epel-release"]'

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Naemon RPMs
        path: ${{ steps.naemon.outputs.rpm_dir_path }}

  build-merlin:
    runs-on: ubuntu-latest
    needs: build-naemon
    steps:
    - uses: actions/checkout@v4

    - uses: actions/download-artifact@v4
      with:
        name: Naemon RPMs

    - run: pwd

    - run: tree

    - name: build Merlin packages
      id: merlin
      uses: UCBoulder/oit-sepe-rpmbuild@master
      with:
        spec_file: "merlin.spec"
        additional_repos: '["epel-release", "/github/home/x86_64/naemon-devel-1.4.2-0.x86_64.rpm"]'

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Merlin RPMs
        path: ${{ steps.merlin.outputs.rpm_dir_path }}

