name: RPM Build
on: push

jobs:
  build-naemon-core:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: build Naemon core packages
      id: build 
      uses: UCBoulder/oit-sepe-rpmbuild@master
      with:
        spec_file: "naemon-core.spec"
        additional_repos: '["epel-release"]'

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Naemon Core RPMs
        path: ${{ steps.build.outputs.rpm_dir_path }}

  build-naemon:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: build Naemon packages
      id: build
      uses: UCBoulder/oit-sepe-rpmbuild@master
      with:
        spec_file: "naemon.spec"
        additional_repos: '["epel-release"]'

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Naemon RPMs
        path: ${{ steps.build.outputs.rpm_dir_path }}

  build-naemon-livestatus:
    runs-on: ubuntu-latest
    needs: build-naemon-core
    steps:
    - uses: actions/checkout@v4

    - uses: actions/download-artifact@v4
      with:
        name: Naemon Core RPMs

    - name: build Naemon Livestatus packages
      id: build
      uses: UCBoulder/oit-sepe-rpmbuild@master
      with:
        spec_file: "naemon-livestatus.spec"
        additional_repos: '["epel-release", "/github/workspace/x86_64/libnaemon-1.4.2-0.x86_64.rpm", "/github/workspace/x86_64/naemon-devel-1.4.2-0.x86_64.rpm"]'

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Naemon Livestatus RPMs
        path: ${{ steps.build.outputs.rpm_dir_path }}

  build-naemon-vimvault:
    runs-on: ubuntu-latest
    needs: build-naemon-core
    steps:
    - uses: actions/checkout@v4

    - uses: actions/download-artifact@v4
      with:
        name: Naemon Core RPMs

    - name: build Naemon Vimvault packages
      id: build
      uses: UCBoulder/oit-sepe-rpmbuild@master
      with:
        spec_file: "naemon-vimvault.spec"
        additional_repos: '["epel-release", "/github/workspace/x86_64/libnaemon-1.4.2-0.x86_64.rpm", "/github/workspace/x86_64/naemon-devel-1.4.2-0.x86_64.rpm"]'

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Naemon Vimvault RPMs
        path: ${{ steps.build.outputs.rpm_dir_path }}

  build-merlin:
    runs-on: ubuntu-latest
    needs: build-naemon-core
    steps:
    - uses: actions/checkout@v4

    - uses: actions/download-artifact@v4
      with:
        name: Naemon Core RPMs

    - name: build Merlin packages
      id: build
      uses: UCBoulder/oit-sepe-rpmbuild@master
      with:
        spec_file: "merlin.spec"
        additional_repos: '["epel-release", "/github/workspace/x86_64/libnaemon-1.4.2-0.x86_64.rpm", "/github/workspace/x86_64/naemon-devel-1.4.2-0.x86_64.rpm"]'

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Merlin RPMs
        path: ${{ steps.build.outputs.rpm_dir_path }}

  build-libthruk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: build Libthruk packages
      id: build
      uses: UCBoulder/oit-sepe-rpmbuild@master
      with:
        spec_file: "libthruk.spec"
        additional_repos: '["epel-release"]'

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Libthruk RPMs
        path: ${{ steps.build.outputs.rpm_dir_path }}

  build-thruk:
    runs-on: ubuntu-latest
    needs: build-libthruk
    steps:
    - uses: actions/checkout@v4

    - uses: actions/download-artifact@v4
      with:
        name: Libthruk RPMs

    - name: build Thruk packages
      id: build
      uses: UCBoulder/oit-sepe-rpmbuild@master
      with:
        spec_file: "thruk.spec"
        additional_repos: '["epel-release", "/github/workspace/x86_64/libthruk-3.00-0.x86_64.rpm"]'

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Thruk RPMs
        path: ${{ steps.build.outputs.rpm_dir_path }}

  build-pnp4nagios:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get install -y rrdtool librrd-dev librrds-perl php-gd php-xml php-mbstring

    - name: What are the perms on rrdtool
      run: ls -la /usr/bin/rrdtool

    - name: run rrdtool
      run: /usr/bin/rrdtool 

    - name: Check if rrdtool is executable
      run: |
        RRDTOOL=/usr/bin/rrdtool
        if ! test -x $RRDTOOL; then
          echo "$RRDTOOL is not executable!"
          exit 1
        else
          echo "$RRDTOOL is executable!"
        fi

    - name: Set 777 on the rrdtool binary just for the hell of it
      run: sudo chmod 777 /usr/bin/rrdtool

    - name: build PNP4Nagios packages
      id: build
      uses: UCBoulder/oit-sepe-rpmbuild@master
      with:
        spec_file: "pnp4nagios.spec"
        additional_repos: '["epel-release"]'

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: PNP4Nagios RPMs
        path: ${{ steps.build.outputs.rpm_dir_path }}

  publish-rpms:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    needs:
      - build-naemon-core
      - build-naemon
      - build-naemon-livestatus
      - build-naemon-vimvault
      - build-libthruk
      - build-thruk
      - build-merlin
      - build-pnp4nagios
    steps:
    - uses: actions/download-artifact@v4
      with:
        merge: true  # Corrected this to 'merge'

    - uses: ncipollo/release-action@v1
      with:
        artifacts: 'x86_64/*,noarch/*'

